name: Node.js CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    name: ci
    runs-on: ubuntu-latest
        
    steps:
      - uses: actions/checkout@v4

      - name: Set Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Build bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: build:prod

      - name: Lint typescript
        uses: borales/actions-yarn@v4
        with:
          cmd: lint:ts

      - name: Test the app
        uses: borales/actions-yarn@v4
        with:
          cmd: test
